### PR TITLE
Use removedev-serialize instead of transit

### PR DESCRIPTION
**Pull request by ntucker**
This will reduce bundle size, and theoretically make it compatible with immutable 4 as well.

Tested by yarn-linking this part to my main project, and everything worked.

### CODE REVIEW

**Comment by rt2zz** [comment]
awesome thank you!

**Comment by ntucker** [comment]
FYI: This will result in previous persisted things not loading right. There should at least be some warnings about the change (an major version bump) so people can handle those cases.

**Comment by rt2zz** [comment]
right, I was going to wait some time to cut a release, also to get an answer here https://github.com/zalmoxisus/remotedev-serialize/issues/4

You bring up a good point, the migration will be painful, probably best handled with a major version bump + a minor with deprecation warnings. That or we could consider moving this into redux-persist core.

**Comment by tborg** [comment]
Say @rt2zz, I wonder if you've thought about cutting a new release for this lately? At this point it seems like the crickets at zalmoxisus/remotedev-serialize#4 indicates a lack of objections.

I have pointed my `package.json` at master and it seems to work great. If you're strapped for time I could have a go at implementing a minor version with deprecation warnings.

**Comment by chrisgbaker** [comment]
Has there been any more thoughts on this? Definitely interested in moving away from having transit-js in our bundles.

**Pull request merged**
